// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGh-P5kpPyYEdml3wTF6H2uzg9qP6xIEk',
    appId: '1:686072940859:web:f46622eb3de76c213a8f1e',
    messagingSenderId: '686072940859',
    projectId: 'tem-videoimage-saver',
    authDomain: 'tem-videoimage-saver.firebaseapp.com',
    storageBucket: 'tem-videoimage-saver.appspot.com',
    measurementId: 'G-M9P3YHQS87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzqvzO3eZlSmAjb4xxGaukz-JGBw-BSV4',
    appId: '1:686072940859:android:16006d979c57a5c13a8f1e',
    messagingSenderId: '686072940859',
    projectId: 'tem-videoimage-saver',
    storageBucket: 'tem-videoimage-saver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbqncuq4kYBR2H9gvu6Ab7Pafo2LxCZYs',
    appId: '1:686072940859:ios:41831c787058855a3a8f1e',
    messagingSenderId: '686072940859',
    projectId: 'tem-videoimage-saver',
    storageBucket: 'tem-videoimage-saver.appspot.com',
    iosBundleId: 'com.example.temFileUploader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbqncuq4kYBR2H9gvu6Ab7Pafo2LxCZYs',
    appId: '1:686072940859:ios:6516e8fa51b72b783a8f1e',
    messagingSenderId: '686072940859',
    projectId: 'tem-videoimage-saver',
    storageBucket: 'tem-videoimage-saver.appspot.com',
    iosBundleId: 'com.example.temFileUploader.RunnerTests',
  );
}
